### ISSUE TITLE
Eclipse code formatting failure in Android studio

### ISSUE THREAD

**Issue by GoogleCodeExporter** [krasa/eclipse-code-formatter-intellij-plugin#65]
```
Error shown : failed to format with Eclipse code formatter. Configured settings 
file does not exist, path=""

```

Original issue reported on code.google.com by `fa...@qburst.com` on 15 Jul 2015 at 9:56

**Comment by krasa** [comment]
"Thank you.Issue has been resolved.
For others, who has the same issue can follow this link- https://github.com/blstream/MyGuide/wiki/%28Android%29-How-to-Add-Eclipse-Code-Formatter-to-Android-Studio."
by fa...@qburst.com
